SET SQL_SAFE_UPDATES=0;
-- DROP PROCEDURE UPDATEFACILITIES
DELIMITER $$
CREATE PROCEDURE UPDATEFACILITIES(VAR_RAW_FACILITY_NAME varchar(255), VAR_FACILITY_ID int, VAR_REP_ID int, VAR_CURRENT_USER int)
BEGIN
    SET @FACILITY_MAP_ID = (SELECT ID FROM Facilities_Rep_Map WHERE LOWER(UGLY_FACILITY) = LOWER(VAR_RAW_FACILITY_NAME) LIMIT 1);
    
    IF @FACILITY_MAP_ID IS NULL THEN
		INSERT INTO Facilities_Rep_Map (UGLY_FACILITY, FACILITY_ID, REP_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE)
		VALUES(VAR_RAW_FACILITY_NAME, VAR_FACILITY_ID, VAR_REP_ID, VAR_CURRENT_USER, CURDATE(), VAR_CURRENT_USER, CURDATE());
		SELECT 'Inserted New Facility and Mapping' AS Status;      
	ELSE 
		UPDATE Facilities_Rep_Map
		SET FACILITY_ID = VAR_FACILITY_ID, REP_ID = VAR_REP_ID, MODIFIED_BY = VAR_CURRENT_USER, MODIFIED_DATE = CURDATE()
		WHERE ID = @FACILITY_MAP_ID;
		SELECT 'Updated Mapping' AS Status;   
    END IF;
END$$
DELIMITER ;